### ISSUE TITLE
Software IRQs are missing

### ISSUE THREAD

**Issue by pta2002** [rp-rs/rp235x-pac#4]
According to the RP235x datasheet, there are 6 spare IRQs which can be used for software interrupts:

| IRQ | Interrupt Source |
|-----|-------------------|
| 46 | `SPAREIRQ_IRQ_0` |
| 47 | `SPAREIRQ_IRQ_1` |
| 48 | `SPAREIRQ_IRQ_2` |
| 49 | `SPAREIRQ_IRQ_3` |
| 50 | `SPAREIRQ_IRQ_4` |
| 51 | `SPAREIRQ_IRQ_5` |

However, these are not exported by this crate.

**Comment by pta2002** [comment]
Looking at the [`SVD file`](https://github.com/raspberrypi/pico-sdk/blob/2.0.0/src/rp2350/hardware_regs/RP2350.svd), it looks like these are missing from there too, so maybe this should be taken up in the Pico SDK.

**Comment by pta2002** [comment]
It seems like embassy's PAC has this working, they probably patched the SVD. I'll see how that can work and will report this upstream.

**Comment by 9names** [comment]
We also use a patch to add the extra IRQ's for rp2040-pac, see 
https://github.com/rp-rs/rp2040-pac/blob/89e78ff078d88cfbbad91bd5aa4eb4ac79a57dab/svd/rp2040.yaml#L766

**Comment by 9names** [comment]
Resolved by #8

**Comment by mfp20** [comment]
It seems like it's not resolved. I can't use any of SPAREIRQ_IRQ_x or SWx_IRQ naming as rtic's dispatchers.
I'm using rp235x-hal = { version = "0.3", optional = true } .

I followed the evolution of this resolution up to the ... ["securing of device.x" fix](https://github.com/rp-rs/rp235x-pac/pull/12) but can't figure out why.

Any clue/tip?
